#!/usr/bin/env bash
set -e
set -x

main() {
  initialise_apt
  install_virtualbox
  install_vmware_vdiskmanager
  install_vagrant
  install_packer
  build_box
  # upload_box
}

initialise_apt() {
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update
}

install_virtualbox() {
  sudo bash -c \
    'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" >> /etc/apt/sources.list'
  curl -L https://www.virtualbox.org/download/oracle_vbox_2016.asc |
    sudo gpg --dearmor --yes --output \
    /usr/share/keyrings/oracle-virtualbox-2016.gpg
  sudo apt-get update
  sudo apt-get -y install virtualbox-7.0
}

install_vmware_vdiskmanager() {
  local archive_path archive_file_path file_name=1023856-vmware-vdiskmanager-linux.7.0.1
  archive_file_path="$(mktemp)"
  curl \
    -L \
    "-o$archive_file_path" \
    -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36' \
    https://kb.vmware.com/sfc/servlet.shepherd/version/download/068f4000009EgK0AAK
  archive_path="$(mktemp -d)"
  pushd "$archive_path"
  unzip "$archive_file_path"
  chmod -v 775 "$file_name"
  sudo mv -v "$file_name" /usr/bin/vmware-vdiskmanager
  popd
  rm -vRf "$archive_file_path" "$archive_path"
  sudo apt-get -y install zlib1g:i386
  # sudo apt-get -y install libc6-i386
  # curl -L "-o$archive_file_path" http://archive.ubuntu.com/ubuntu/pool/universe/o/openssl098/libssl0.9.8_0.9.8o-7ubuntu3.1_i386.deb
  # sudo dpkg -i "$archive_file_path"
  # rm -vRf "$archive_file_path"
  # sudo apt-get -y -f install
}

install_vagrant() {
  local vagrant_deb

  vagrant_deb="$(mktemp)"
  curl -L "-o$vagrant_deb" \
    https://releases.hashicorp.com/vagrant/2.3.7/vagrant_2.3.7-1_amd64.deb
  sudo dpkg -i "$vagrant_deb"
  rm -v "$vagrant_deb"
  sudo apt-get -y -f install
  vagrant plugin install vagrant-disksize
}

install_packer() {
  curl -L https://apt.releases.hashicorp.com/gpg | \
    sudo gpg --dearmor --yes -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  sudo bash -c \
    'echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list'
  sudo apt-get update
  sudo apt-get -y install packer
}

build_box() {
  VAGRANT_EXPERIMENTAL=disks \
    PKR_VAR_box_version="$SEMAPHORE_GIT_TAG_NAME" \
    packer build main.pkr.hcl
  ls -lh output-example
  # return
  mkdir -v package
  pushd package
  tar zxvf ../output-example/package.box
  ls -lh
  aws s3 cp box-disk001.vmdk s3://s3-archive-bucket-12lood0bp4x5v/
  find . -name '*.vmdk' \
    -exec vmware-vdiskmanager -d {} ';' \
    -exec vmware-vdiskmanager -k {} ';'
  ls -lh
  exit
  rm -v ../output-example/package.box
  tar zcvf ../output-example/package.box *
  popd
}

upload_box() {
  tar tf output-example/package.box
  sha1sum < output-example/package.box | tee "package-$SEMAPHORE_GIT_TAG_NAME.box.sha1sum"
  aws s3 cp "package-$SEMAPHORE_GIT_TAG_NAME.box.sha1sum" \
    "s3://s3-archive-bucket-12lood0bp4x5v/package-$SEMAPHORE_GIT_TAG_NAME.box.sha1sum"
  aws s3 cp output-example/package.box \
    "s3://s3-archive-bucket-12lood0bp4x5v/package-$SEMAPHORE_GIT_TAG_NAME.box"
}

[ -z "$SEMAPHORE_GIT_TAG_NAME" ] || main
